const students = [
    { no: 6018, name: "Ramazan Miran İlhan", gender: "Erkek" },
{ no: 6231, name: "Tırtarlı Erdem", gender: "Erkek" },
    { no: 6205, name: "Kadir Cahit Alcan", gender: "Erkek" },
    { no: 6209, name: "Köksal Buluklu", gender: "Erkek" },
    { no: 621, name: "Yasin Kılıçarslan", gender: "Erkek" },
    { no: 611, name: "Yasin Kılıçarslan", gender: "Erkek" },
    { no: 211, name: "Yasin Kılıçarslan", gender: "Erkek" },
    { no: 699, name: "Celal Çelik", gender: "Erkek" },
    { no: 6214, name: "Mehmet Emin Onat", gender: "Erkek" },
    { no: 6215, name: "Çağrı Kağan Dölek", gender: "Erkek" },
    { no: 6220, name: "Ahmet Kaya", gender: "Erkek" },
    { no: 6224, name: "Ahmed Feridun Güneş", gender: "Erkek" },
    { no: 6226, name: "Çağan Gökgündüz", gender: "Erkek" },
    { no: 61, name: "Yasin Kılıçarslan", gender: "Erkek" },
    { no: 651, name: "Yasin Kılıçarslan", gender: "Erkek" },
    { no: 6229, name: "Emir Turan Erdoğan", gender: "Erkek" },
    { no: 6231, name: "Tırtarlı Erdem", gender: "Erkek" },
    { no: 6232, name: "Emirhan Ayhan", gender: "Erkek" }
{ no: 2371, name: "Tırtarlı Erdem", gender: "Erkek" },
{ no: 0000, name: "Mirket", gender: "Erkek" },
];