const students = [
    { no: 6002, name: "Büra Tetik", gender: "Kız" },
    { no: 6018, name: "Ramazan Miran İlhan", gender: "Erkek" },
    { no: 6203, name: "Ümit Arda Özbek", gender: "Erkek" },
    { no: 6204, name: "Emine Tuğba Uysal", gender: "Kız" },
    { no: 6205, name: "Kadir Cahit Alcan", gender: "Erkek" },
    { no: 6206, name: "Elif Fatma Yurtçiçek", gender: "Kız" },
    { no: 6207, name: "Seher Savuş", gender: "Kız" },
    { no: 6208, name: "Cemre Zehra Çetin", gender: "Kız" },
    { no: 6209, name: "Köksal Buluklu", gender: "Erkek" },
    { no: 6210, name: "Şevval Koçak", gender: "Kız" },
    { no: 6211, name: "Yasin Kılıçarslan", gender: "Erkek" },
    { no: 6212, name: "Celal Çelik", gender: "Erkek" },
    { no: 6213, name: "Elif Ece", gender: "Kız" },
    { no: 6214, name: "Mehmet Emin Onat", gender: "Erkek" },
    { no: 6215, name: "Çağrı Kağan Dölek", gender: "Erkek" },
    { no: 6219, name: "Berat Mil", gender: "Erkek" },
    { no: 6220, name: "Ahmet Kaya", gender: "Erkek" },
    { no: 6221, name: "Elmira Topuz", gender: "Kız" },
    { no: 6222, name: "Bengü Sude Karakuş", gender: "Kız" },
    { no: 6223, name: "Kıyasettin Alper Şen", gender: "Erkek" },
    { no: 6224, name: "Ahmed Feridun Güneş", gender: "Erkek" },
    { no: 6225, name: "Ela Tuana Küpüç", gender: "Kız" },
    { no: 6226, name: "Çağan Gökgündüz", gender: "Erkek" },
    { no: 6227, name: "Hayrunisa Bilgin", gender: "Kız" },
    { no: 6229, name: "Emir Turan Erdoğan", gender: "Erkek" },
    { no: 6230, name: "Birsen Kuru", gender: "Kız" },
    { no: 6231, name: "Erdem Şahin", gender: "Erkek" },
    { no: 6232, name: "Emirhan Ayhan", gender: "Erkek" },
    { no: 6233, name: "İrem Su Bilir", gender: "Kız" },
    { no: 6234, name: "Semanur Er", gender: "Kız" },
    { no: 6321, name: "Nilay Tekgöz", gender: "Kız" },
    { no: 6324, name: "Medine Yumru", gender: "Kız" },
    { no: 6326, name: "İrem Eşki", gender: "Kız" },
    { no: 6330, name: "Eda Altundaş", gender: "Kız" },
    { no: 6334, name: "Damla Solmaz", gender: "Kız" },
    { no: 6335, name: "Meys Bekke", gender: "Kız" },
    { no: 6336, name: "Yagut Guliyeva", gender: "Kız" },
    { no: 6338, name: "Melek Alalı", gender: "Kız" },
    { no: 6347, name: "Ela Aslan", gender: "Kız" }
];
